### ISSUE TITLE
用 mask 实现应该更清晰

### ISSUE THREAD

**Issue by expkzb** [lizelu/ZLCustomeSegmentControlView#3]
一层正常label，二层红底白色label，在二层上加一个圆角矩形 mask

**Comment by YouXianMing** [comment]
用mask非常容易 http://www.cnblogs.com/YouXianMing/p/4125132.html

**Comment by sgflamel** [comment]
去看了原blog，本来想在blog里评论，懒得注册就打算回来在issue里提，看到已经有人提到了，这个view确实用mask实现起来极其简单。。也不用那么多高深的理论

**Comment by lizelu** [comment]
@fyt10060
之前也写过Mask的Demo，连接如下:http://www.cnblogs.com/ludashi/p/5671133.html
